// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel1;
void ui_event_Arc4(lv_event_t * e);
extern lv_obj_t * ui_Arc4;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
void ui_event_Arc3(lv_event_t * e);
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label7;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image3;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_441806990);    // assets/Snipaste_2024-05-05_16-43-04.png
LV_IMG_DECLARE(ui_img_89729788);    // assets/Snipaste_2024-05-18_13-29-56.png
LV_IMG_DECLARE(ui_img_1277231463);    // assets/Snipaste_2024-05-18_16-04-53.png
LV_IMG_DECLARE(ui_img_45962382);    // assets/ebadf792-0b88-460f-b5cc-dbb6ec494373.png



LV_FONT_DECLARE(ui_font_fton16);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
